import {
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ConfigService } from '@nestjs/config';
import * as QRCode from 'qrcode';
import PDFDocument from 'pdfkit';
import { QrCode } from './entities/qr-code.entity';
import { Store, StoreStatus } from '../stores/entities/store.entity';
import { CreateQrResponseDto } from './dto/create-qr.dto';
import { StoreAnalyticsService } from '../store-analytics/store-analytics.service';

@Injectable()
export class QrService {
  constructor(
    @InjectRepository(QrCode)
    private readonly qrCodeRepository: Repository<QrCode>,
    @InjectRepository(Store)
    private readonly storeRepository: Repository<Store>,
    private readonly configService: ConfigService,
    private readonly analyticsService: StoreAnalyticsService,
  ) {}

  async getActiveQr(storeId: string, ownerId: string): Promise<CreateQrResponseDto> {
    const qr = await this.findActiveQr(storeId, ownerId);
    const scanUrl = this.buildScanUrl(qr.token);
    const qrImageUrl = await QRCode.toDataURL(scanUrl, {
      errorCorrectionLevel: 'H',
      margin: 2,
      width: 512,
      color: { dark: '#000000', light: '#FFFFFF' },
    });

    return {
      id: qr.id,
      storeId: qr.storeId,
      token: qr.token,
      isActive: qr.isActive,
      createdAt: qr.createdAt,
      qrImageUrl,
      scanUrl,
    };
  }

  async createQr(storeId: string, ownerId: string): Promise<CreateQrResponseDto> {
    const store = await this.verifyOwnership(storeId, ownerId);

    if (store.status === StoreStatus.INACTIVE) {
      throw new ForbiddenException(
        'Gian hàng cần được Admin kích hoạt trước khi tạo QR code.',
      );
    }

    // Invalidate all active QRs for this store
    await this.qrCodeRepository.update(
      { storeId, isActive: true },
      { isActive: false },
    );

    // Create new QR (token generated by DB default)
    const qr = this.qrCodeRepository.create({
      storeId,
      createdBy: ownerId,
      isActive: true,
    });
    const saved = await this.qrCodeRepository.save(qr);

    const scanUrl = this.buildScanUrl(saved.token);
    const qrImageUrl = await QRCode.toDataURL(scanUrl, {
      errorCorrectionLevel: 'H',
      margin: 2,
      width: 512,
      color: { dark: '#000000', light: '#FFFFFF' },
    });

    return {
      id: saved.id,
      storeId: saved.storeId,
      token: saved.token,
      isActive: saved.isActive,
      createdAt: saved.createdAt,
      qrImageUrl,
      scanUrl,
    };
  }

  async getActivePng(storeId: string, ownerId: string): Promise<Buffer> {
    const qr = await this.findActiveQr(storeId, ownerId);
    const scanUrl = this.buildScanUrl(qr.token);
    return QRCode.toBuffer(scanUrl, {
      errorCorrectionLevel: 'H',
      margin: 2,
      width: 512,
    });
  }

  async getActivePdf(storeId: string, ownerId: string): Promise<Buffer> {
    const qr = await this.findActiveQr(storeId, ownerId);
    const store = await this.storeRepository.findOne({ where: { id: storeId } });
    const storeName = store?.name ?? `Gian hàng #${storeId}`;

    const scanUrl = this.buildScanUrl(qr.token);
    const pngDataUrl = await QRCode.toDataURL(scanUrl, {
      errorCorrectionLevel: 'H',
      margin: 2,
      width: 512,
    });
    const base64Data = pngDataUrl.replace(/^data:image\/png;base64,/, '');
    const pngBuffer = Buffer.from(base64Data, 'base64');

    return new Promise((resolve) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      doc.fontSize(16).text(storeName, { align: 'center' });
      doc.moveDown();
      doc.image(pngBuffer, { fit: [300, 300], align: 'center' });
      doc.moveDown();
      doc
        .fontSize(10)
        .text('Quét mã QR để xem chi tiết gian hàng', { align: 'center' });

      doc.end();
    });
  }

  async resolveToken(token: string): Promise<string | 'unavailable'> {
    const result = await this.resolveTokenData(token);
    if (result.type === 'unavailable') return 'unavailable';
    return result.storeId;
  }

  async resolveTokenData(
    token: string,
  ): Promise<{ type: 'store'; storeId: string } | { type: 'unavailable' }> {
    const qr = await this.qrCodeRepository.findOne({
      where: { token },
      relations: ['store'],
    });

    if (!qr || !qr.isActive) return { type: 'unavailable' };

    const store = qr.store;
    if (!store || store.status === StoreStatus.INACTIVE) return { type: 'unavailable' };

    this.analyticsService.track(store.id, 'qr_scan');
    return { type: 'store', storeId: store.id };
  }

  private async verifyOwnership(storeId: string, ownerId: string): Promise<Store> {
    const store = await this.storeRepository.findOne({ where: { id: storeId } });
    if (!store) throw new NotFoundException('Gian hàng không tồn tại.');
    if (store.ownerId !== ownerId) {
      throw new ForbiddenException('Bạn không sở hữu gian hàng này.');
    }
    return store;
  }

  private async findActiveQr(storeId: string, ownerId: string): Promise<QrCode> {
    await this.verifyOwnership(storeId, ownerId);

    const qr = await this.qrCodeRepository.findOne({
      where: { storeId, isActive: true },
    });
    if (!qr) throw new NotFoundException('Gian hàng chưa có QR code active nào.');

    return qr;
  }

  private buildScanUrl(token: string): string {
    const base =
      this.configService.get<string>('APP_BASE_URL') || 'http://localhost:3000';
    return `${base}/qr/${token}`;
  }
}
